import { Inter } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import ThemeProviderClientWrapper from "../components/ThemeProviderClientWrapper";
import LanguageToggleButton from "../components/LanguageSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const messages = await getMessages();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviderClientWrapper>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </ThemeProviderClientWrapper>
      </body>
    </html>
  );
}
